import {
  EXPO_PUBLIC_AI_API_KEY,
  EXPO_PUBLIC_EMAIL_JS,
  EXPO_PUBLIC_EMAIL_PUBLIC_KEY,
  EXPO_PUBLIC_EMAIL_SERVICE_ID,
  EXPO_PUBLIC_EMAIL_TEMPLATE_ID,
  EXPO_PUBLIC_FIREBASE_API_KEY,
  EXPO_PUBLIC_FIREBASE_APP_ID,
  EXPO_PUBLIC_FIREBASE_GOOGLE_WEB_CLIENT_ID,
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
} from "@env";

export const openAiApiKey = EXPO_PUBLIC_AI_API_KEY;
export const emailServiceId = EXPO_PUBLIC_EMAIL_SERVICE_ID;
export const emailTemplateId = EXPO_PUBLIC_EMAIL_TEMPLATE_ID;
export const emailPublicKey = EXPO_PUBLIC_EMAIL_PUBLIC_KEY;
export const emailJs = EXPO_PUBLIC_EMAIL_JS;
export const firebaseApiKey = EXPO_PUBLIC_FIREBASE_API_KEY;
export const firebaseMessagingSenderId =
  EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const firebaseAppId = EXPO_PUBLIC_FIREBASE_APP_ID;
export const googleWebClientId = EXPO_PUBLIC_FIREBASE_GOOGLE_WEB_CLIENT_ID;
