export default {
  yes: "Yes",
  error: "Error",
  close: "Close",
  register: "Register",
  login: "Login",
  usernamePlaceholder: "username",
  emailPlaceholder: "your@welcome.com",
  passwordPlaceholder: "#password",
  agePlaceholder: "age",
  somethingWentWrong: "Something went wrong!",
  verify: "Verify",
  verifyCode: "Verify code",
  enterCode: "Please enter the code we just sent to email",
  noReceivedCode: "Didn’t receive OTP?",
  resendCode: "Resend code",
  userAlreadyExists: "User already exists!",
  userAlreadyExistsDescription: "Try using another email or login",
  codeIsIncorrect: "Code is incorrect! Try again",
};
