export default {
  yes: "Yes",
  error: "Error",
  close: "Close",
  register: "Register",
  login: "Login",
  usernamePlaceholder: "username",
  emailPlaceholder: "your@welcome.com",
  passwordPlaceholder: "#password",
  agePlaceholder: "age",
  somethingWentWrong: "Something went wrong!",
  verify: "Verify",
  verifyCode: "Verify code",
  enterCode: "Please enter the code we just sent to email",
  noReceivedCode: "Didn’t receive OTP?",
  resendCode: "Resend code",
  userAlreadyExists: "User already exists!",
  userAlreadyExistsDescription: "Try using another email or login",
  codeIsIncorrect: "Code is incorrect! Try again",
  incorrectEmailOrPassword: "Incorrect email or password",
  logout: "Logout",
  noInternetConnection: "No internet connection",
  retry: "Retry",
  chooseYoursFirstModel: "Choose yours first model",
  thisChoiceCanBeChangedAfter: "This choice can be changed after",
  getStarted: "Get started",
  findYourModel: "Find your model",
  goodChoice: "Good choice!!!",
  modelName: "Model name",
  music: "Music",
  addons: "Addons",
  sport: "Sport",
  games: "Games",
  photo: "Photo",
  money: "Money",
  smart: "Smart",
  find: "Find",
  select: "SELECT",
  findAgain: "Find again",
  hello: "Hello",
  readyToBecomeYourModel: "Ready to become your model?",
  yourModelIsNow: "Your model is now",
  strike: "Strike",
  motivation: "Motivation",
  food: "Food",
  todayNumberOfMeals: "Today number of meals",
  freeTime: "Free time",
  gym: "Gym",
  todayWeHit: "Today we hit",
  contactYourMentor: "Contact your mentor",
  findANewMentor: "Find a new mentor",
  changeTheModel: "Are you sure you want to change your Model?",
  yesPlease: "Yes, please",
  noLikeThisOne: "No, I like this one",
  leavingSoSoon: "Are you leaving so soon?",
  yesLogout: "Yes, logout",
  noItWasMistake: "No, it was a mistake",
  challenge: "Challenge",
  fails: "Fails",
  yourStatsFrom: "Your stats from",
  currentModel: "Current model",
  what: "What",
  eats: "eats?",
  whatIs: "What is",
  workoutRoutine: "workout routine?",
  monday: "Monday",
  tuesday: "Tuesday",
  wednesday: "Wednesday",
  thursday: "Thursday",
  friday: "Friday",
  saturday: "Saturday",
  sunday: "Sunday",
  activities: "Activities",
};
