export const IconAssets = {
  send: "send",
  lock: "lock",
  lockSolid: "lock-solid",
  check: "check",
  pieChart: "pie-chart",
  arrowBack: "arrow-back",
  settings: "settings",
  starEmpty: "star-empty",
  arrowUpDown: "arrow-up-down",
  arrowDown: "arrow-down",
  circleUser: "circle-user",
  mail: "mail",
  eye: "eye",
  eyeBlocked: "eye-blocked",
};
