export const Lottie = {
  createAccount: require("./createAccount.json"),
  lit: require("./lit.json"),
  aiBot: require("./aiBot.json"),
  tap: require("./tap.json"),
  aiLoading: require("./aiLoading.json"),
  dragon: require("./dragon.json"),
  chill: require("./chill.json"),
  sport: require("./sport.json"),
  influencer: require("./influencer.json"),
  astronaut: require("./astronaut.json"),
  pizza: require("./pizza.json"),
  error: require("./error.json"),
  reload: require("./reload.json"),
};
