import {
  FIREBASE_APP,
  FIREBASE_REALTIME_DB,
  FIREBASE_STORAGE_PHOTOS_MODEL_PATH,
} from "./config";

export {
  FIREBASE_APP,
  FIREBASE_REALTIME_DB,
  //path
  FIREBASE_STORAGE_PHOTOS_MODEL_PATH,
};
